# Generated by Django 4.0.5 on 2022-06-16 12:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
            ],
        ),
    ]
