# Generated by Django 4.0.5 on 2022-06-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='full_name',
        ),
    ]
